#!/usr/bin/env bash
# The script displays "Best School" 10 times using a while loop.
# And also displays "Hi" on the 9th iteration before "Best School".

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( count++ ))
done
