#!/usr/bin/env bash
# A bash script that displays the contents of the current directory in a list form
#   Only displays the part of the name after the first dash. 

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
